services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: mathhelper
      POSTGRES_PASSWORD: mh_secret_2026
      POSTGRES_DB: mathhelper
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    restart: unless-stopped
    ports:
      - "4011:3001"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://mathhelper:mh_secret_2026@db:5432/mathhelper
      - JWT_SECRET=mathhelper_secret_key_2026
      - PORT=3001
      - GOOGLE_CLIENT_ID=1004475773858-nondip8br7f0imavgej0vpm4gn6ld5pn.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - VAPID_PUBLIC_KEY=BM8GWvox2a8ttm4QE0l-RVECH6mxsX-5PojWYvhK1WUBHSZwgZhpIa2CcltWTP9-DRABSo_RT-NmcydKKK1iP7A
      - VAPID_PRIVATE_KEY=oNfGzAdTjMYj1GsO8OIpddJV6ZpozQDGZBPlQK0XLnY

volumes:
  pgdata:
